pull_request_rules:
  - name: automatic merge for dependeabot
    conditions:
      - and:
          - "author=dependabot[bot]"
          - or:
              - "title~=Bump axios from"
              - "title~=Bump core-js from"
    actions:
      merge:
        method: rebase
